## Put comments here that give an overall description of what your
## functions do

##The code below will cache the inverse of a matrix

## Write a short comment describing this function:

##this first function creates an R object that can store the
##inverse of a matrix.  

makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
    set <- function(y) { 
        x <<- y
        i <<- NULL
    }
    get <- function() x
    setinv <- (solve(x)) i <<- solve(x)
    getinv <- function() i
    list(set = set, get = get,
         setinv = setinv, 
         getinv = getinv)
}


## Write a short comment describing this function

##the second function is necessary to compute the inverse of the
##matrix generated by the first function

cacheSolve <- function(x, ...) {
    i <- x$getinv()
    if(!is.null(i)) { 
        message("getting cached data")
        return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinv(i)
    i
        ## Return a matrix that is the inverse of 'x'
}
